title: Random Thoughts
email: iamshuqian@gmail.com
description: >-
  ©️ Designed by shuq3 & An0nym6
baseurl: ""
url: "https://shuq3.github.io/"  # 发布时应更改
github_username:  shuq3
markdown: kramdown
paginate: 8
paginate_path: "/page:num/"
jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
